name: LamdaDeploy


on:
 push:
   branches:
      - main

jobs:
   deploy_Lamda:
     runs-on: unbuntu-latest
     steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-python-@v2 
          with:
              python-version: 3.8
